### PR TITLE
Allow for filter bypass for cellua achievement

### PR DESCRIPTION
**Pull request by youtissoum**
I fix your achievements pt.1

### CODE REVIEW

**Comment by youtissoum** [comment]
pull request now

**Comment by youtissoum** [comment]
very important

**Review by milena-kos — CHANGES_REQUESTED** [review]
why this specifically? i feel like this is an unintuitive bypass and there are other ones

**Comment by youtissoum** [comment]
ok I'll do regex

**Comment by ZakChrom** [comment]
frog

**Pull request closed without merging**
