### PR TITLE
crashDifficulty++

### PR DESCRIPTION
**Pull request by NathanCrazy**

### CODE REVIEW

**Comment by milena-kos** [comment]
that is a good idea but what the fuck why are you adding +20 there and +60 there

**Comment by milena-kos** [comment]
there is also no apparent reason to round it

**Comment by NathanCrazy** [comment]
why am i rounding it? because i want to increase computer load
as for the plus 60 thing im actually stupid there was an idea there but it failed

**Comment by milena-kos** [comment]
:clap: :trollface:

**Comment by milena-kos** [comment]
what the fuck this is worse

**Comment by NathanCrazy** [comment]
alright should (?) be good now
i am also absolutely only doing this because i just got crasher in cat stand and i want it to be rarer

**Comment by NathanCrazy** [comment]
oh its bad? damn

**Review by milena-kos — APPROVED** [review]
buddy can NOT stop yapping

**Pull request merged**
