### PR TITLE
prevent placeholder emoji cats spawning

### PR DESCRIPTION
**Pull request by uku1928**
because catching them does nothing

### CODE REVIEW

**Comment by uku1928** [comment]
on second thought this doesn't feel that important
people just gonna have to cope with not being able to catch 🔳 cats

**Comment by rech2020** [comment]
h

**Comment by milena-kos** [comment]
this should also be less important with new restart system

**Comment by milena-kos** [comment]
i thought about storing cattypes in alt text for cat image or even get this - storing it in db, but that doesnt seem necessary

**Pull request closed without merging**
