### PR TITLE
Make it so that tsuu doesn't kill me

### PR DESCRIPTION
**Pull request by NathanCrazy**

### CODE REVIEW

**Comment by milena-kos** [comment]
murder is glod

**Comment by milena-kos** [comment]
good

**Comment by NathanCrazy** [comment]
glod is so real

**Comment by TsuuCore** [comment]
Lock your windows Nathan you are fucked 🔪

**Comment by Aflyde** [comment]
does he have at least a house where he can close them

**Comment by TsuuCore** [comment]
Eh If he does I'll just bring a nuke if he doesn't I'll just bring a nuke wither way nuke is very effective

**Comment by TsuuCore** [comment]
Changing weapon method to nuke

**Comment by NathanCrazy** [comment]
im vaccinated tho :staring_cat:

**Comment by milena-kos** [comment]
nuh uh

**Comment by NathanCrazy** [comment]
bro just unvaccinated me :staring_cat:

**Comment by milena-kos** [comment]
indeed im just that powerful :sungals:

**Comment by NathanCrazy** [comment]
fr 💣

**Comment by TsuuCore** [comment]
Why did it matter that you're vaccinated for a nuke 🐀

**Comment by NathanCrazy** [comment]
nuke vaccines have a NaN% success rate

**Comment by TsuuCore** [comment]
I make my own special nukes why would a vaccine for typical nukes affect a completely different nuke

**Comment by milena-kos** [comment]
is your nuke glarded?

**Comment by TsuuCore** [comment]
> is your nuke glarded?

Yea why

**Comment by TsuuCore** [comment]
> i want to nuke lia this is NOT ash from not ash

whatever you say, Ash

**Comment by MonkeysWithPie** [comment]
hey they _just said_ they weren't Ash

**Comment by TsuuCore** [comment]
> hey they _just said_ they weren't Ash

I have trust issues with fox girls /j

**Comment by TsuuCore** [comment]
Foxes are cheeky and mischievous

**Comment by TsuuCore** [comment]
Take sniper from uhh Dora I think that's his name as an example

**Comment by TsuuCore** [comment]
Sniper no sniping 🦊

**Comment by Ashanorie** [comment]
> > i want to nuke lia this is NOT ash from not ash
> 
> whatever you say, Ash

IT WASNT ME

**Comment by MonkeysWithPie** [comment]
> Foxes are cheeky and mischievous
i'm in love with a fox boy is this gonna be an issue

**Comment by Ashanorie** [comment]
> hey they _just said_ they weren't Ash

yeah it wasn’t me

**Comment by TsuuCore** [comment]
> > Foxes are cheeky and mischievous
> 
> i'm in love with a fox boy is this gonna be an issue

I think chroma is an acception

**Comment by MonkeysWithPie** [comment]
> I think chroma is an acception

noted

**Comment by TsuuCore** [comment]
> > > i want to nuke lia this is NOT ash from not ash
> > 
> > 
> > whatever you say, Ash
> 
> IT WASNT ME

I no believe you 🦊

**Comment by Ashanorie** [comment]
> > hey they _just said_ they weren't Ash
> 
> I have trust issues with fox girls /j

i’m just a silly fox girl man :(

**Comment by Ashanorie** [comment]
> > > > i want to nuke lia this is NOT ash from not ash
> > > 
> > > 
> > > whatever you say, Ash
> > 
> > 
> > IT WASNT ME
> 
> I no believe you 🦊

YIP YIP

**Comment by TsuuCore** [comment]
> > > hey they _just said_ they weren't Ash
> > 
> > 
> > I have trust issues with fox girls /j
> 
> i’m just a silly fox girl man :(

Yea and I bet you're sniper from Dora the explorer in Disguise 🥸

**Comment by Ashanorie** [comment]
> > > > hey they _just said_ they weren't Ash
> > > 
> > > 
> > > I have trust issues with fox girls /j
> > 
> > 
> > i’m just a silly fox girl man :(
> 
> Yea and I bet you're sniper from Dora the explorer in Disguise 🥸

dora dora dora the explorerrerr

**Comment by TsuuCore** [comment]
And the name you go bye
**ash**anorie
Mmhhmmmmmmmmmmmmm 🤔

**Comment by TsuuCore** [comment]
download (43)

**Comment by Ashanorie** [comment]
> And the name you go bye
> **ash**anorie
> Mmhhmmmmmmmmmmmmm 🤔

REHURGDUDHEIEHRIEBEJEVHRRBEGEUEGSGS
RHATS MY MEXICAN TWIN BROTHER
BDJSVSJEBEIEGSFUL AROYSRKYSFSU

**Comment by TsuuCore** [comment]
> > And the name you go bye
> > **ash**anorie
> > Mmhhmmmmmmmmmmmmm 🤔
> 
> REHURGDUDHEIEHRIEBEJEVHRRBEGEUEGSGS RHATS MY MEXICAN TWIN BROTHER BDJSVSJEBEIEGSFUL AROYSRKYSFSU

FYM THATS YOUR TWIN BROTHER ITS YOUR USERNAME
YOUR
USERNAME

**Comment by Ashanorie** [comment]
> > > And the name you go bye
> > > **ash**anorie
> > > Mmhhmmmmmmmmmmmmm 🤔
> > 
> > 
> > REHURGDUDHEIEHRIEBEJEVHRRBEGEUEGSGS RHATS MY MEXICAN TWIN BROTHER BDJSVSJEBEIEGSFUL AROYSRKYSFSU
> 
> FYM THATS YOUR TWIN BROTHER ITS YOUR USERNAME YOUR USERNAME


TJDHEIEVEJEVEU

**Comment by Ashanorie** [comment]
meow meow meow

**Comment by TsuuCore** [comment]
> > > > And the name you go bye
> > > > **ash**anorie
> > > > Mmhhmmmmmmmmmmmmm 🤔
> > > 
> > > 
> > > REHURGDUDHEIEHRIEBEJEVHRRBEGEUEGSGS RHATS MY MEXICAN TWIN BROTHER BDJSVSJEBEIEGSFUL AROYSRKYSFSU
> > 
> > 
> > FYM THATS YOUR TWIN BROTHER ITS YOUR USERNAME YOUR USERNAME
> 
> TJDHEIEVEJEVEU

01000010 01100001 01101100 01101100 01110011 to you too

**Comment by Ashanorie** [comment]
> > > > > And the name you go bye
> 
> > > > > **ash**anorie
> 
> > > > > Mmhhmmmmmmmmmmmmm 🤔
> 
> > > > 
> 
> > > > 
> 
> > > > REHURGDUDHEIEHRIEBEJEVHRRBEGEUEGSGS RHATS MY MEXICAN TWIN BROTHER BDJSVSJEBEIEGSFUL AROYSRKYSFSU
> 
> > > 
> 
> > > 
> 
> > > FYM THATS YOUR TWIN BROTHER ITS YOUR USERNAME YOUR USERNAME
> 
> > 
> 
> > TJDHEIEVEJEVEU
> 
> 
> 
> 01000010 01100001 01101100 01101100 01110011 to you too

oh shit am i being hacked

**Comment by TsuuCore** [comment]
> > > > > > And the name you go bye
> > 
> > 
> > > > > > **ash**anorie
> > 
> > 
> > > > > > Mmhhmmmmmmmmmmmmm 🤔
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > REHURGDUDHEIEHRIEBEJEVHRRBEGEUEGSGS RHATS MY MEXICAN TWIN BROTHER BDJSVSJEBEIEGSFUL AROYSRKYSFSU
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > FYM THATS YOUR TWIN BROTHER ITS YOUR USERNAME YOUR USERNAME
> > 
> > 
> > > 
> > 
> > 
> > > TJDHEIEVEJEVEU
> > 
> > 
> > 01000010 01100001 01101100 01101100 01110011 to you too
> 
> oh shit am i being hacked

Uhh yeah sure ig (no)
01010100 01110011 01110101 01110101 00100000 01101001 01110011 00100000 01001010 01100101 01110011 01110101 01110011 00100000 01001010 01100101 01110011 01110101 01110011 00100000 01101001 01110011 00100000 01010100 01110011 01110101 01110101

**Comment by Ashanorie** [comment]
> > > > > > > And the name you go bye
> 
> > > 
> 
> > > 
> 
> > > > > > > **ash**anorie
> 
> > > 
> 
> > > 
> 
> > > > > > > Mmhhmmmmmmmmmmmmm 🤔
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > REHURGDUDHEIEHRIEBEJEVHRRBEGEUEGSGS RHATS MY MEXICAN TWIN BROTHER BDJSVSJEBEIEGSFUL AROYSRKYSFSU
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > FYM THATS YOUR TWIN BROTHER ITS YOUR USERNAME YOUR USERNAME
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > TJDHEIEVEJEVEU
> 
> > > 
> 
> > > 
> 
> > > 01000010 01100001 01101100 01101100 01110011 to you too
> 
> > 
> 
> > oh shit am i being hacked
> 
> 
> 
> Uhh yeah sure ig (no)
> 
> 01010100 01110011 01110101 01110101 00100000 01101001 01110011 00100000 01001010 01100101 01110011 01110101 01110011 00100000 01001010 01100101 01110011 01110101 01110011 00100000 01101001 01110011 00100000 01010100 01110011 01110101 01110101

stop hacking me /j

**Comment by TsuuCore** [comment]
Cry abt it 
729384932984838388

**Comment by Ashanorie** [comment]
> Cry abt it
> 729384932984838388

STOPPPPYHHHTHTHHHHTHTHYHUHHHHH

**Comment by TsuuCore** [comment]
Womp womp 838388373773736273893869693784849483737337637282736463738292

**Comment by milena-kos** [comment]
this is definetely

**Comment by milena-kos** [comment]
hold on where is the button

**Pull request closed without merging**
