### PR TITLE
how to english ¿¿¿??? forogoro?

### PR DESCRIPTION
**Pull request by NathanCrazy**

### CODE REVIEW

**Comment by milena-kos** [comment]
changing ach id will effectively wipe that achievement from all existing users, if you really want you should only change display name or make a migrator

im not merging this anyway but

**Comment by Ashanorie** [comment]
wuh oh

**Comment by milena-kos** [comment]
im also not sure why did you add `# fix` in a lot of places but whatever

**Comment by NathanCrazy** [comment]
because I didn't want to make a migrator

**Comment by frinkifail** [comment]
very epic fixes

**Comment by NotRealAz** [comment]
how to english

**Pull request closed without merging**
