### PR TITLE
Update aches.json

### PR DESCRIPTION
**Pull request by Jgabby08**
Marrying the cat would be amazing just because

### CODE REVIEW

**Comment by ZakChrom** [comment]
its impossible to get the ach :cat_nerd:

**Comment by Jgabby08** [comment]
What if just saying "Cat I do" gives the achievement

**Review by Jgabby08 — COMMENTED** [review]
Is this fine?

**Comment by milena-kos** [comment]
no

**Comment by milena-kos** [comment]
1. make the ach id be styled correctly
2. add hints or change the way you get it (e.g. "cat do you want to marry me?", just saying "Cat i do" without context is weird)
3. move it further down in the file
4. actually code it. if you wont this should go to #ach-ideas in [cat stand](https://discord.gg/staring)

**Comment by frinkifail** [comment]
marriage is literally spelled wrong

**Comment by milena-kos** [comment]
closing for stale

**Pull request closed without merging**
