### PR TITLE
Add back point laugh reaction

### PR DESCRIPTION
**Pull request by ZakChrom**
Since the event server isn't causing problems anymore we can add it back :thubm_up:

### CODE REVIEW

**Comment by NathanCrazy** [comment]
the funny thing is that comment is there for a reason there was a command there

**Comment by ZakChrom** [comment]
Oh I didn't see that in the changes
I'll add it to the pull once i get on pc

**Comment by ZakChrom** [comment]
Oh wait I'm stupid
That's an old thing I think

**Comment by milena-kos** [comment]
i think a good compromise would be to implement some kind of channel-/server-wide ratelimit on those reactions

**Comment by ZakChrom** [comment]
yeah i think that is the easiest way

**Pull request closed without merging**
