### PR TITLE
No "Join our Discord!" on Cat Stand server

### PR DESCRIPTION
**Pull request by eliaswolfy**
why?

### CODE REVIEW

**Comment by NathanCrazy** [comment]
Join our Discord!

**Comment by milena-kos** [comment]
Join our Discord!

**Comment by uku1928** [comment]
Join our Discord!

**Comment by ZakChrom** [comment]
Join our Discord!

**Comment by eliaswolfy** [comment]
This is definitely a "Join our Discord!" moment

**Comment by NathanCrazy** [comment]
tbh what you're suggesting makes complete sense but the way that it is is funny so

**Comment by eliaswolfy** [comment]
🤯

**Pull request closed without merging**
