### PR TITLE
burger pt 2

### PR DESCRIPTION
**Pull request by MonkeysWithPie**
change "Battlepass level" to say "Cattlepass level" instead

### CODE REVIEW

**Comment by miko0087** [comment]
yessssssssss

**Comment by MonkeysWithPie** [comment]
look at me being helpful
also this is my first time using github lol

**Comment by uku1928** [comment]
I like this
No battles in this bot (just a reaction game I guess)
Added pun
Cat theme
just excellent overall

**Comment by milena-kos** [comment]
then do you think it would make more sense to replace every mention of it by this point

**Review by milena-kos — APPROVED** [review]
actually i think thats almost every mention lgtm

**Pull request merged**
