### PR TITLE
Speed up casino

### PR DESCRIPTION
**Pull request by uku1928**
I made spins go faster by about 64%

### CODE REVIEW

**Review by frinkifail — APPROVED** [review]
qhar

**Comment by khag7** [comment]
Is this a rate limit issue? Does discord allow to update the messages faster?

**Comment by frinkifail** [comment]
no i think its code performance because for loops aren't rate limited ._.

**Comment by khag7** [comment]
The for loop isn't rate limited.  What a silly thing to suggest

interaction.edit_original_response is rate limited

**Comment by milena-kos** [comment]
its an interaction endpoint so it doesnt affect the global ratelimit, but it can still trip channel ratelimit if multiple people spin at once

**Comment by khag7** [comment]
Makes sense. I guess there's probably a low low risk of it being an issue, so improved code performance is probably worth it

**Comment by uku1928** [comment]
I just wanted people to wait less to get the casino achievements

**Comment by milena-kos** [comment]
Suffering is absolutely necessary.

**Comment by therealten95** [comment]
nuh uh

**Comment by milena-kos** [comment]
i think its funnier and more dramatic if it goes through all the options

**Pull request closed without merging**
