### PR TITLE
Split up embeds

### PR DESCRIPTION
**Pull request by VishramKidPG123**
make function to split embed fields into pages or something (discord only lets you have a max of 25 fields per embed)
currently this is used for /inventory
it may also be able to be implemented into /leaderboard
this will be used in /whohas once I code that

### CODE REVIEW

**Comment by frinkifail** [comment]
chat vishram kid pg 123 is cooking again
unfortunately he's cooking with air currently

**Comment by frinkifail** [comment]
also i mean atleast do like
```py
async def something():
    pass
```
instead of `async def something()`
idk i just thought it'd be more clear that its to be implemented

**Comment by frinkifail** [comment]
i mean you dont have to

**Comment by VishramKidPG123** [comment]
lol yeah I'll actually code this once I have time at some point

**Comment by milena-kos** [comment]
im not merging this cus i feel like it can break and it wont ever be used in main cat bot

**Comment by VishramKidPG123** [comment]
true, it wouldn't be used in main cat bot unless more than 25 cats are added
I'll just keep in my own fork then

**Comment by VishramKidPG123** [comment]
actually I just realized this would be used in the /whohas command that I was planning to make

**Comment by VishramKidPG123** [comment]
could this maybe be reopened once my whohas command is working idk

**Comment by frinkifail** [comment]
vishramkidpg123 is braining

**Pull request closed without merging**
